### PR TITLE
Added windows arm64 support

### PR DESCRIPTION
**Pull request by Binozo**
Hey 👋

I am currently working with this project on an arm64 machine and thus added windows arm64 support

### CODE REVIEW

**Comment by sappho192** [comment]
Hi @Binozo !
Sorry for the late reply, and it looks good to me!

I'll release the next version with this changes today (if there's no other problem).

**Comment by sappho192** [comment]
Hi, @Binozo ,

It seems to have a breaking changes to support(handle) the multiple windows architecture.
Mainly I need to reissue the nuget package ID and some tests, but it won't take so long I think.

**Comment by Binozo** [comment]
Yeah sure, take your time!

If there's something I broke and can fix, just tell me 👨‍🏭

**Comment by sappho192** [comment]
Further discussions will be on #13 .

**Pull request merged**
